const PlantasList = [
    {
        nome: 'Bromélia', img: './plantas/bromelias.jpeg',
        tipo: 'planta',
        preco: 0, medidas: '?x?', tamanho: '?',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 40, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Bromélia 2', img: './plantas/bromelia2.png',
        tipo: 'planta',
        preco: 0, medidas: '?x?', tamanho: '?',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 45, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Pleomele Variegata', img: './plantas/pleomeleVariegata.jpeg',
        tipo: 'planta',
        preco: 40, medidas: '?x?', tamanho: 'PT8',
        preco2: 120, medidas2: '?x?', tamanho2: '11L',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Buxinho', img: './plantas/buxinho.jpeg',
        tipo: 'planta',
        preco: 65, medidas: '?x?', tamanho: '20L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Buxinho Trabalhado', img: './plantas/buxinhoTrab.jpeg',
        tipo: 'planta',
        preco: 150, medidas: '?x?', tamanho: '18L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Leia Rubra / Verde', img: 'https://images.tcdn.com.br/img/img_prod/753894/muda_de_leia_rubra_altura_de_0_40_cm_a_0_80_cm_673_1_8617fa6b705b0d8ffc57e0130df74f9e.jpg',
        tipo: 'planta',
        preco: 90, medidas: '?x?', tamanho: '15L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Pingo de Ouro', img: './plantas/pingoOuro.jpeg',
        tipo: 'planta',
        preco: 30, medidas: '?x?', tamanho: '?',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
//    {
//       nome: 'Sagu de Jardim', img: './plantas/pingoOuro.jpeg',
//      tipo: 'planta',
//        preco: 30, medidas: '?x?', tamanho: '?',
//        preco2: 0, medidas2: '?x?', tamanho2: '?',
//        preco3: 0, medidas3: '?x?', tamanho3: '?',
//        preco4: 0, medidas4: '?x?', tamanho4: '?',
//        preco5: 0, medidas5: '?x?', tamanho5: '?',
//    },
    {
        nome: 'Palmeira Veitchia', img: 'https://cdn.awsli.com.br/800x800/935/935548/produto/35493736/c3e8006c42.jpg',
        tipo: 'planta',
        preco: 170, medidas: '?x?', tamanho: '25L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Moreia', img: './plantas/moreia.png',
        tipo: 'planta',
        preco: 20, medidas: '?x?', tamanho: '5L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Kaizuka', img: 'https://images.tcdn.com.br/img/img_prod/1173196/kaizuka_emb_8l_705_1_17ee21b525276d9f73fd42a3d6cd6314.jpg',
        tipo: 'planta',
        preco: 550, medidas: '?x?', tamanho: '?',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Cruzia', img: 'https://brasilnativas.com.br/wp-content/uploads/2021/01/clusia.png',
        tipo: 'planta',
        preco: 18, medidas: '?x?', tamanho: '?',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },
    {
        nome: 'Jabuticaba', img: './plantas/jabuticaba.png',
        tipo: 'planta',
        preco: 200, medidas: '?x?', tamanho: '20L',
        preco2: 0, medidas2: '?x?', tamanho2: '?',
        preco3: 0, medidas3: '?x?', tamanho3: '?',
        preco4: 0, medidas4: '?x?', tamanho4: '?',
        preco5: 0, medidas5: '?x?', tamanho5: '?',
    },

]

export default PlantasList;