import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import VasosCim from '../components/vasosCim';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/vasosCimento/guirlandaLiso.jpg" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <button>Vasos de Cimento</button>
          <button>Vasos de Barro</button>
        </div>
        <VasosCim />
      </main>
    </>
  )
}
